filter:
  excluded_paths:
    - 'Documentation/*'
    - 'Tests/*'
    - 'Resources/Public/JavaScript/*'
  paths:
    - 'Classes/*'
  dependency_paths:
    - ".Build/vendor"

tools:
  php_cpd:
    enabled: true

  php_code_sniffer:
    enabled: true
    config:
      standard: TYPO3CMS

  # we do this on travis
  php_cs_fixer:
    enabled: false

  php_mess_detector:
    enabled: true
    config:
      controversial_rules:
        superglobals: false

  php_pdepend:
    enabled: true

  php_analyzer:
    enabled: true

  external_code_coverage:
    runs: 2
    timeout: 2400

checks:
    php:
        excluded_dependencies:
            - typo3/cms-install
        avoid_superglobals: false

build:
  environment:
    # We want to test with the smallest supported by TYPO3 PHP version
    php: 7.2
  dependencies:
    override:
      - composer install --dev --no-interaction --no-scripts
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev squizlabs/php_codesniffer:^3.6
#      tests:
#        override:
#          - php-scrutinizer-run
#          - command: phpcs-run
#            use_website_config: false
