services:
  _defaults:
    autowire: false
    autoconfigure: true

  ApacheSolrForTypo3\Tika\:
    resource: '../Classes/*'

  backend_controller:
    namespace: ApacheSolrForTypo3\Tika\Controller\Backend\SolrModule\
    resource: '../Classes/Controller/Backend/SolrModule/*'
    public: true
    autowire: true
    tags: ['backend.controller']
