services:
  _defaults:
    autowire: false
    autoconfigure: true

  ApacheSolrForTypo3\Tika\:
    resource: '../Classes/*'

  ApacheSolrForTypo3\Tika\Lowlevel\EventListener\BlindedSecrets:
    tags:
      - name: event.listener
        identifier: 'tika/blind-secrets-for-tika'
        event: 'TYPO3\CMS\Lowlevel\Event\ModifyBlindedConfigurationOptionsEvent'
